version: '3.8'

services:
  db:
    restart: always
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env  # Specify the environment file for the db service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # web:
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile.prod
  #   command: >
  #     sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     DB_NAME: alxhof_db
  #     DB_USER: alxhof_admin
  #     DB_PASSWORD: abc
  #     DB_HOST: db
  #     DB_PORT: 5433
  #   env_file:
  #     - .env  # Specify the environment file for the web service

  # adminer:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080

volumes:
  postgres_data:
