### DISPLAYING ALL USERS
GET http://localhost:8000/users
Content-Type: application/json

{}

### DELETING A USER
DELETE http://localhost:8000/users/2
Content-Type: application/json

{}

### Test JWT token
GET http://localhost:8000/test_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5MDYyMjgzLCJpYXQiOjE3MTkwNTg2MjEsImp0aSI6ImZhZDcxYjIwODIxMDRiYTk5M2U4NjEwYjJiMDhkNzJiIiwidXNlcl9pZCI6M30.Jeg26Mxfh9GNdJTfWNgm62n4jcU-gd7qguLbYfSqWTk

### Trying to post something on behalf of user 3
POST http://localhost:8000/projects/create_with_token/

Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5MDYyMjgzLCJpYXQiOjE3MTkwNTg2MjEsImp0aSI6ImZhZDcxYjIwODIxMDRiYTk5M2U4NjEwYjJiMDhkNzJiIiwidXNlcl9pZCI6M30.Jeg26Mxfh9GNdJTfWNgm62n4jcU-gd7qguLbYfSqWTk

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="projectTitle"

My New Project
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="authors"

John Doe, Jane Smith
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

This is a new project description.
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tags"

Tag1, Tag2
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="githubRepos"

https://github.com/myusername/myproject
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="liveProject"

https://myproject.com
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imgFile"; filename="project_image.jpg"
Content-Type: image/jpeg

[Binary image data]
----WebKitFormBoundary7MA4YWxkTrZu0gW--


### New comment
curl -X POST http://localhost:8000/api/comments/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzMxMDE5LCJpYXQiOjE3MTk2NDQ2MTksImp0aSI6IjBhN2MwZjcwMTg3ZDRkODM5NGJmNGYxOTIwYzYyYjIyIiwidXNlcl9pZCI6MX0.Tj56M3yT5PGx8FEhKBx29A238IntHYhBHMDK_qmAatM" \
     -d '{"content": "This is a comment"}'


### DELETING A COMMENT
curl -X DELETE http://localhost:8000/api/projects/1/comments/1/ -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5ODg5Njg4LCJpYXQiOjE3MTk4MDMyODgsImp0aSI6IjIyNDAzMmFmOTQwMjQ0NmY4NGJkNTMyNGM4NWYxOTQ4IiwidXNlcl9pZCI6MX0.TIMLigm7yOd902CQQ6TIGReVYFQg8lC-Aydga3SYC7U"


### Testing collaborators
GET https://api.github.com/repos/bravemaster3/huhola/collaborators
Authorization: Bearer <token>
Accept: application/vnd.github.v3+json
