POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "bravemaster", "password": "office"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "bravemaster", "password": "office", "email": "bravemaster102@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 7e36105aa35b0f46e8e956b6a3992bb870964df1

{}

###

GET http://127.0.0.1:8000/all_users
Content-Type: application/json

{}

###

DELETE http://127.0.0.1:8000/userx/4
Content-Type: application/json

{}
